
# cargo-vet audits file

[[audits.bytes]]
who = "gknopf <gknopf@spideroak.com>"
criteria = "safe-to-deploy"
delta = "1.9.0 -> 1.10.0"

[[audits.bytes]]
who = "Steve Sweetney <ssweetney@spideroak.com>"
criteria = "safe-to-deploy"
delta = "1.10.1 -> 1.11.1"
notes = "Code updates align with release notes. Replaced instances of unchecked arithmetic. New tests added to verify fixes."

[[audits.derive-where]]
who = "Jonathan Dygert <jdygert@spideroak.com>"
criteria = "safe-to-deploy"
version = "1.5.0"

[[audits.elain]]
who = "Jonathan Dygert <jdygert@spideroak.com>"
criteria = "safe-to-deploy"
version = "0.3.1"

[[audits.futures-timer]]
who = "Jonathan Dygert <jdygert@spideroak.com>"
criteria = "safe-to-run"
version = "3.0.3"

[[audits.hashbrown]]
who = "Jonathan Dygert <jdygert@spideroak.com>"
criteria = "safe-to-deploy"
delta = "0.16.0 -> 0.16.1"

[[audits.itertools]]
who = "Eric Lagergren <elagergren@spideroak.com>"
criteria = "safe-to-deploy"
delta = "0.11.0 -> 0.13.0"

[[audits.macro-string]]
who = "Jonathan Dygert <jdygert@spideroak.com>"
criteria = "safe-to-deploy"
version = "0.1.4"

[[audits.matchers]]
who = "Jonathan Dygert <jdygert@spideroak.com>"
criteria = "safe-to-deploy"
delta = "0.1.0 -> 0.2.0"

[[audits.nu-ansi-term]]
who = "Jonathan Dygert <jdygert@spideroak.com>"
criteria = "safe-to-deploy"
delta = "0.46.0 -> 0.50.1"

[[audits.proc-macro-crate]]
who = "Jonathan Dygert <jdygert@spideroak.com>"
criteria = "safe-to-run"
delta = "2.0.1 -> 3.3.0"

[[audits.rcgen]]
who = "Jonathan Dygert <jdygert@spideroak.com>"
criteria = "safe-to-run"
delta = "0.11.3 -> 0.13.2"

[[audits.rkyv]]
who = "Jonathan Dygert <jdygert@spideroak.com>"
criteria = "safe-to-deploy"
delta = "0.8.11 -> 0.8.13"

[[audits.rkyv_derive]]
who = "Jonathan Dygert <jdygert@spideroak.com>"
criteria = "safe-to-deploy"
delta = "0.8.11 -> 0.8.13"

[[audits.rstest]]
who = "Jonathan Dygert <jdygert@spideroak.com>"
criteria = "safe-to-run"
delta = "0.22.0 -> 0.26.1"

[[audits.rstest_macros]]
who = "Jonathan Dygert <jdygert@spideroak.com>"
criteria = "safe-to-run"
delta = "0.22.0 -> 0.26.1"

[[audits.scc]]
who = "Jonathan Dygert <jdygert@spideroak.com>"
criteria = "safe-to-run"
delta = "2.2.6 -> 2.3.3"

[[audits.sdd]]
who = "Jonathan Dygert <jdygert@spideroak.com>"
criteria = "safe-to-run"
delta = "3.0.5 -> 3.0.7"

[[audits.serde_test]]
who = "Jonathan Dygert <jdygert@spideroak.com>"
criteria = "safe-to-run"
version = "1.0.177"

[[audits.sha3-utils]]
who = "Eric Lagergren <elagergren@spideroak.com>"
criteria = "safe-to-deploy"
delta = "0.3.0 -> 0.5.0"

[[audits.spin]]
who = "Eric Lagergren <elagergren@spideroak.com>"
criteria = "safe-to-deploy"
delta = "0.9.8 -> 0.10.0"

[[audits.syn]]
who = "Jonathan Dygert <jdygert@spideroak.com>"
criteria = "safe-to-deploy"
delta = "2.0.90 -> 2.0.101"

[[audits.tokio]]
who = "Jonathan Dygert <jdygert@spideroak.com>"
criteria = "safe-to-deploy"
delta = "1.41.1 -> 1.44.2"

[[audits.tokio-macros]]
who = "Jonathan Dygert <jdygert@spideroak.com>"
criteria = "safe-to-deploy"
delta = "2.4.0 -> 2.5.0"

[[audits.tracing-subscriber]]
who = "Jonathan Dygert <jdygert@spideroak.com>"
criteria = "safe-to-deploy"
delta = "0.3.19 -> 0.3.20"

[[audits.zerocopy]]
who = "Eric Lagergren <elagergren@spideroak.com>"
criteria = "safe-to-deploy"
delta = "0.7.35 -> 0.8.25"

[[audits.zerocopy-derive]]
who = "Eric Lagergren <elagergren@spideroak.com>"
criteria = "safe-to-deploy"
delta = "0.7.35 -> 0.8.25"

[[trusted.anstream]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-03-16"
end = "2026-11-19"

[[trusted.anstyle]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2022-05-18"
end = "2026-11-19"

[[trusted.anstyle-parse]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-03-08"
end = "2026-11-19"

[[trusted.anstyle-query]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-04-13"
end = "2026-11-19"

[[trusted.anstyle-wincon]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-03-08"
end = "2026-11-19"

[[trusted.aranya-afc-util]]
criteria = "safe-to-deploy"
user-id = 293722 # aranya-project-bot
start = "2024-10-16"
end = "2025-12-19"

[[trusted.aranya-bearssl-sys]]
criteria = "safe-to-deploy"
user-id = 293722 # aranya-project-bot
start = "2024-10-15"
end = "2025-12-19"

[[trusted.aranya-capi-codegen]]
criteria = "safe-to-deploy"
user-id = 293722 # aranya-project-bot
start = "2024-11-08"
end = "2025-12-19"

[[trusted.aranya-capi-core]]
criteria = "safe-to-deploy"
user-id = 293722 # aranya-project-bot
start = "2024-11-08"
end = "2025-12-19"

[[trusted.aranya-capi-macro]]
criteria = "safe-to-deploy"
user-id = 293722 # aranya-project-bot
start = "2024-11-08"
end = "2025-12-19"

[[trusted.aranya-crypto]]
criteria = "safe-to-deploy"
user-id = 293722 # aranya-project-bot
start = "2024-10-16"
end = "2025-12-19"

[[trusted.aranya-crypto-ffi]]
criteria = "safe-to-deploy"
user-id = 293722 # aranya-project-bot
start = "2024-10-16"
end = "2025-12-19"

[[trusted.aranya-device-ffi]]
criteria = "safe-to-deploy"
user-id = 293722 # aranya-project-bot
start = "2024-10-16"
end = "2025-12-19"

[[trusted.aranya-envelope-ffi]]
criteria = "safe-to-deploy"
user-id = 293722 # aranya-project-bot
start = "2024-10-16"
end = "2025-12-19"

[[trusted.aranya-fast-channels]]
criteria = "safe-to-deploy"
user-id = 293722 # aranya-project-bot
start = "2024-10-16"
end = "2025-12-19"

[[trusted.aranya-idam-ffi]]
criteria = "safe-to-deploy"
user-id = 293722 # aranya-project-bot
start = "2024-10-16"
end = "2025-12-19"

[[trusted.aranya-libc]]
criteria = "safe-to-deploy"
user-id = 293722 # aranya-project-bot
start = "2024-11-08"
end = "2025-12-19"

[[trusted.aranya-perspective-ffi]]
criteria = "safe-to-deploy"
user-id = 293722 # aranya-project-bot
start = "2024-10-16"
end = "2025-12-19"

[[trusted.aranya-policy-ast]]
criteria = "safe-to-deploy"
user-id = 293722 # aranya-project-bot
start = "2024-10-16"
end = "2025-12-19"

[[trusted.aranya-policy-compiler]]
criteria = "safe-to-deploy"
user-id = 293722 # aranya-project-bot
start = "2024-10-16"
end = "2025-12-19"

[[trusted.aranya-policy-derive]]
criteria = "safe-to-deploy"
user-id = 293722 # aranya-project-bot
start = "2024-10-16"
end = "2025-12-19"

[[trusted.aranya-policy-ifgen]]
criteria = "safe-to-deploy"
user-id = 293722 # aranya-project-bot
start = "2024-10-16"
end = "2025-12-19"

[[trusted.aranya-policy-ifgen-build]]
criteria = "safe-to-deploy"
user-id = 293722 # aranya-project-bot
start = "2024-10-16"
end = "2025-12-19"

[[trusted.aranya-policy-ifgen-macro]]
criteria = "safe-to-deploy"
user-id = 293722 # aranya-project-bot
start = "2024-10-16"
end = "2025-12-19"

[[trusted.aranya-policy-lang]]
criteria = "safe-to-deploy"
user-id = 293722 # aranya-project-bot
start = "2024-10-16"
end = "2025-12-19"

[[trusted.aranya-policy-module]]
criteria = "safe-to-deploy"
user-id = 293722 # aranya-project-bot
start = "2024-10-16"
end = "2025-12-19"

[[trusted.aranya-policy-vm]]
criteria = "safe-to-deploy"
user-id = 293722 # aranya-project-bot
start = "2024-10-16"
end = "2025-12-19"

[[trusted.aranya-runtime]]
criteria = "safe-to-deploy"
user-id = 293722 # aranya-project-bot
start = "2024-10-16"
end = "2025-12-19"

[[trusted.buggy]]
criteria = "safe-to-deploy"
user-id = 293722 # aranya-project-bot
start = "2025-01-24"
end = "2026-01-24"

[[trusted.clap_builder]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-03-28"
end = "2026-11-19"

[[trusted.clap_lex]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2022-04-15"
end = "2026-11-19"

[[trusted.colorchoice]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-04-13"
end = "2026-11-19"

[[trusted.is_terminal_polyfill]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2024-05-02"
end = "2026-11-19"

[[trusted.spideroak-base58]]
criteria = "safe-to-deploy"
user-id = 293722 # aranya-project-bot
start = "2025-01-24"
end = "2025-12-19"

[[trusted.spideroak-crypto]]
criteria = "safe-to-deploy"
user-id = 293722 # aranya-project-bot
start = "2025-01-23"
end = "2026-01-23"

[[trusted.spideroak-crypto-derive]]
criteria = "safe-to-deploy"
user-id = 293722 # aranya-project-bot
start = "2025-01-23"
end = "2026-01-23"

[[trusted.toml_datetime]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2022-10-21"
end = "2026-11-19"

[[trusted.toml_edit]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2021-09-13"
end = "2026-11-19"

[[trusted.toml_parser]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2025-07-08"
end = "2026-11-19"

[[trusted.winnow]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-02-22"
end = "2026-11-19"
